// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzacclaffklenqmmtsad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6YWNjbGFmZmtsZW5xbW10c2FkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0MDU1MjMsImV4cCI6MjA1Mzk4MTUyM30.GBeFNcqmCR7ZEgZqeCJgvdW9GkPl0EtKHucoIcl5NoI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);